/**
 * H5X Validation Test Runner
 *
 * This program runs the validation test suite to ensure the obfuscation
 * system is working correctly and all metrics accurately reflect the
 * actual obfuscation performed.
 */

#include "../src/core/ReportValidator.hpp"
#include <iostream>
#include <vector>
#include <string>
#include <fstream>

struct TestCase {
    std::string name;
    std::string sourceFile;
    std::string expectedStrings;
    std::string expectedArithmeticOps;
    std::string expectedControlFlow;
    std::string expectedFunctions;
};

class ValidationTestRunner {
public:
    ValidationTestRunner() {
        setupTestCases();
    }

    bool runAllTests() {
        std::cout << "H5X Validation Test Suite" << std::endl;
        std::cout << "=========================" << std::endl;

        bool allPassed = true;
        int totalTests = 0;
        int passedTests = 0;

        for (const auto& testCase : testCases_) {
            totalTests++;
            if (runSingleTest(testCase)) {
                passedTests++;
            } else {
                allPassed = false;
            }
        }

        std::cout << "\nTest Results Summary:" << std::endl;
        std::cout << "Total Tests: " << totalTests << std::endl;
        std::cout << "Passed: " << passedTests << std::endl;
        std::cout << "Failed: " << (totalTests - passedTests) << std::endl;
        std::cout << "Success Rate: " << (static_cast<double>(passedTests) / totalTests * 100.0) << "%" << std::endl;

        return allPassed;
    }

private:
    void setupTestCases() {
        testCases_ = {
            {
                "String Obfuscation Test",
                "demos/validation_test_strings.cpp",
                "8", // Expected 8 strings to be obfuscated
                "0", // No arithmetic operations
                "0", // No control flow modifications expected
                "1"  // Main function
            },
            {
                "Arithmetic Operations Test",
                "demos/validation_test_arithmetic.cpp",
                "0", // No strings
                "20", // Expected ~20 arithmetic operations
                "0", // No control flow modifications expected
                "1"  // Main function
            },
            {
                "Control Flow Test",
                "demos/validation_test_control_flow.cpp",
                "0", // No strings
                "0", // No arithmetic operations
                "5", // Expected control flow modifications
                "1"  // Main function
            },
            {
                "Function Calls Test",
                "demos/validation_test_functions.cpp",
                "3", // Expected strings in function calls
                "5", // Expected arithmetic operations
                "2", // Expected control flow modifications
                "12" // Multiple functions
            }
        };
    }

    bool runSingleTest(const TestCase& testCase) {
        std::cout << "\nRunning test: " << testCase.name << std::endl;
        std::cout << "----------------------------------------" << std::endl;

        // Check if source file exists
        std::ifstream sourceFile(testCase.sourceFile);
        if (!sourceFile.is_open()) {
            std::cout << "ERROR: Source file not found: " << testCase.sourceFile << std::endl;
            return false;
        }
        sourceFile.close();

        // Generate expected output filenames
        std::string baseName = testCase.sourceFile.substr(0, testCase.sourceFile.find_last_of('.'));
        std::string jsonReport = baseName + ".report.json";
        std::string htmlReport = baseName + ".report.html";
        std::string textReport = baseName + ".report.txt";

        // Check if reports exist (would be generated by obfuscation process)
        std::ifstream jsonFile(jsonReport);
        std::ifstream htmlFile(htmlReport);
        std::ifstream textFile(textReport);

        if (!jsonFile.is_open() || !htmlFile.is_open() || !textFile.is_open()) {
            std::cout << "WARNING: Report files not found. Run obfuscation first." << std::endl;
            std::cout << "Expected: " << jsonReport << ", " << htmlReport << ", " << textReport << std::endl;
            return false;
        }

        jsonFile.close();
        htmlFile.close();
        textFile.close();

        // Validate reports
        h5x::ReportValidator validator;

        auto jsonValidation = validator.validateJsonReport(jsonReport);
        auto htmlValidation = validator.validateHtmlReport(htmlReport);
        auto textValidation = validator.validateTextReport(textReport);

        // Print validation results
        printValidationResult("JSON Report", jsonValidation);
        printValidationResult("HTML Report", htmlValidation);
        printValidationResult("Text Report", textValidation);

        // Check cross-format consistency
        bool consistent = validator.validateReportConsistency(jsonReport, htmlReport, textReport);
        std::cout << "Cross-format consistency: " << (consistent ? "PASS" : "FAIL") << std::endl;

        if (!consistent) {
            std::cout << "WARNING: Reports are not consistent across formats" << std::endl;
        }

        // Validate against expected metrics
        bool metricsValid = validateExpectedMetrics(jsonValidation, testCase);

        bool passed = jsonValidation.overallSuccess &&
                     htmlValidation.overallSuccess &&
                     textValidation.overallSuccess &&
                     consistent &&
                     metricsValid;

        std::cout << "Test result: " << (passed ? "PASS" : "FAIL") << std::endl;
        return passed;
    }

    void printValidationResult(const std::string& reportType, const h5x::ValidationReport& result) {
        std::cout << reportType << " Validation:" << std::endl;
        std::cout << "  Overall: " << (result.overallSuccess ? "PASS" : "FAIL") << std::endl;
        std::cout << "  Score: " << result.overallScore << "/100" << std::endl;
        std::cout << "  Metrics: " << result.passedMetrics << "/" << result.totalMetrics << " passed" << std::endl;

        if (result.failedMetrics > 0) {
            std::cout << "  Failures: " << result.failedMetrics << std::endl;
            for (const auto& failure : result.criticalFailures) {
                std::cout << "    - " << failure << std::endl;
            }
            for (const auto& warning : result.warnings) {
                std::cout << "    * " << warning << std::endl;
            }
        }
    }

    bool validateExpectedMetrics(const h5x::ValidationReport& report, const TestCase& testCase) {
        std::cout << "Validating expected metrics:" << std::endl;

        bool allValid = true;

        // This would need to be implemented based on actual metric extraction
        // from the validation report
        std::cout << "  Expected strings: " << testCase.expectedStrings << std::endl;
        std::cout << "  Expected arithmetic: " << testCase.expectedArithmeticOps << std::endl;
        std::cout << "  Expected control flow: " << testCase.expectedControlFlow << std::endl;
        std::cout << "  Expected functions: " << testCase.expectedFunctions << std::endl;

        // Placeholder - would need actual metric validation logic
        std::cout << "  NOTE: Detailed metric validation not yet implemented" << std::endl;

        return allValid;
    }

    std::vector<TestCase> testCases_;
};

int main() {
    ValidationTestRunner runner;

    bool success = runner.runAllTests();

    if (success) {
        std::cout << "\nAll validation tests passed!" << std::endl;
        return 0;
    } else {
        std::cout << "\nSome validation tests failed." << std::endl;
        return 1;
    }
}